### PR TITLE
1925: Sharing of lists improved

### PR DESCRIPTION
**Pull request by martinb14**
http://platform.dandigbib.org/issues/1925

### CODE REVIEW

**Comment by cableman** [comment]
Please look into the scrutinizer notifications.

**Comment by cableman** [comment]
Please follow the guidelines for commit messages.

> [issue number]: [short summary of change]. The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

Writing ".a" and ".b" is not a valid commit message when you are sitting in a terminal looking at the history.

**Comment by cableman** [comment]
Also the commit "Ad hoc fixes" why is this related to issue http://platform.dandigbib.org/issues/1925 ?

**Comment by martinb14** [comment]
Do we delete this pr, re-pull without the ad hoc commits, and create a hotfix with the ad hoc commit?

**Comment by DDBdrift** [comment]
https://platform.dandigbib.org/issues/1925 | Resolved (tag version)

**Pull request closed without merging**
