### PR TITLE
3452: Fix meta description for events, datetime + price.

### PR DESCRIPTION
**Pull request by rasben**
#### Link to issue
https://platform.dandigbib.org/issues/3452

#### Description

The <meta name="description"> field has wrong data.
- The time is being outputted in the wrong timezone, meaning its different from what is displayed on the page.
- The date time only shows beginning time, not the interval
- When the price is not set, it's meant to say "Free" - This hasnt been translated to danish

Before:
```
<meta name="description" 
content="Mød Sofie Kragh-Müller, forfatter og medlem af det eksperimenterende musikfællesskab LUCY BLOOM., 
Biblioteket Frederiksberg - Lyttetrappen, 12.04.2018 - 15:00, free">
````

After:
````
<meta name="description" 
content="Mød Sofie Kragh-Müller, forfatter og medlem af det eksperimenterende musikfællesskab LUCY BLOOM., 
Biblioteket Frederiksberg - Lyttetrappen, 12.04.2018 - 17:00 - 18:00, gratis">
````

#### Checklist

- [x] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [x] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [x] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

### CODE REVIEW

**Comment by holt83** [comment]
The price value on ding_event can contain a string, and it doesn't necessarily makes sense to append a currency. See: https://github.com/ding2/ding2/blob/master/modules/ding_event/ding_event.module#L394

**Comment by rasben** [comment]
@holt83 
I follow your thinking and I've updated it here:
https://github.com/ding2/ding2/compare/3ade88786660026c108b291022e79e0065633ee6..b0ad1910fd5ac6fa2488f6bbe319edc07cad148d

But in a way, it's a bit silly that it's a textfield in the first place

The field description says they can use intervals such as "50 - 60", and in that case there wouldnt be any automatic "kr" suffix..

So to make it less confusing i've added a "Price:" prefix

**Comment by holt83** [comment]
Thanks 👍 

I was also against it to begin with, but there's a lot of argumentation in https://platform.dandigbib.org/issues/4286

> So to make it less confusing i've added a "Price:" prefix
Makes sense :)

**Comment by rasben** [comment]
@holt83 Does that mean i can have an approve? :D 😇

**Comment by JrgenGNielsen** [comment]
reviewed and approved

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: ea6e202a3cc23ad6b1eb7d504a7f9948ba8a219f
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: ea6e202a3cc23ad6b1eb7d504a7f9948ba8a219f
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
