### PR TITLE
Platform.sh integration

### PR DESCRIPTION
**Pull request by kasperg**
#### Link to issue

https://platform.dandigbib.org/issues/4652

#### Description

This PR includes configuration and changes required for using Platform.sh with Ding2. Please read the individual commit comments for further details.

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

### CODE REVIEW

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 8cde68ba100be4c7c3a5f3f90402d1511f8c3ee9
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 505d82c0cc07cc2cf00b908c4f37dbdc690dece9
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 27b784994ed9ba5e18a138226987d84e9552fa22
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: e5b136a91efca67cb667e2d45b8bd642eb780122
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 416dae29ceeb45c774a49b437a701afb7e5f3e78
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: b622351ee893200df9b50ef203cfb23e6f13ea42
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: d301b93d95dcc9f9863b75e349ed6ec7969f9d2c
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: a3bfe92eed9c2622a689da6a45d3f336f8dfc734
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 4c14aac90341484f5b2afea9f3804f698ba9684c
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 8cde68ba100be4c7c3a5f3f90402d1511f8c3ee9
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 505d82c0cc07cc2cf00b908c4f37dbdc690dece9
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 27b784994ed9ba5e18a138226987d84e9552fa22
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: e5b136a91efca67cb667e2d45b8bd642eb780122
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 416dae29ceeb45c774a49b437a701afb7e5f3e78
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: b622351ee893200df9b50ef203cfb23e6f13ea42
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: d301b93d95dcc9f9863b75e349ed6ec7969f9d2c
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: a3bfe92eed9c2622a689da6a45d3f336f8dfc734
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 4c14aac90341484f5b2afea9f3804f698ba9684c
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by JrgenGNielsen** [comment]
Looks good, with the aber dabei that I don't have much experience with platform.sh configuration.
... and I suppose I ought to chastise you for the invalid commit messages ;-)

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 8ec8586d25705b2b1a2a867d1ded019a84fa75f6
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 79701ead92cb162815a706d3dbc24355f5dea85e
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 67795c2337bf9f288baca3428f839b4c9e6b879d
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 54cc7773c236a82d9c26a321983b8daa1be300f4
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: ea0f505b8c07fb060940c1c6cef860206cd34522
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 613108a47c9f639ff08373c6bb9130056af01277
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 3ca75ece6b6b5f943e510c0af2f57a1264bdffd9
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: e083af8766543efad713ddac8998f0917a506c4d
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 008ff3e8fb02c34bcfb1151a1e01203779a43f2a
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 8ec8586d25705b2b1a2a867d1ded019a84fa75f6
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 79701ead92cb162815a706d3dbc24355f5dea85e
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 67795c2337bf9f288baca3428f839b4c9e6b879d
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 54cc7773c236a82d9c26a321983b8daa1be300f4
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: ea0f505b8c07fb060940c1c6cef860206cd34522
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 613108a47c9f639ff08373c6bb9130056af01277
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 3ca75ece6b6b5f943e510c0af2f57a1264bdffd9
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: e083af8766543efad713ddac8998f0917a506c4d
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 008ff3e8fb02c34bcfb1151a1e01203779a43f2a
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
