### PR TITLE
1770: Slick for search carousel

### PR DESCRIPTION
**Pull request by xendk**
Replaces old carousel library with slick.

Also some bugfixes.

### CODE REVIEW

**Comment by guddo** [comment]
What about all other changes in #261?

**Comment by xendk** [comment]
Shouldn't be too hard for you to merge ind. I have the new code working in a custom field, so rendering it in a ctools content type shouldn't prove to be a problem.

**Comment by guddo** [comment]
That's a lot of hassle since we'll have to wait for this to be merged, before we can proceed.

**Comment by xendk** [comment]
I've improved the theming, improved UX by limiting loading jumps and using placeholders for unloaded content. And improved performance by using a queue for loading to there's only one active Ajax request at a time.

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: b1aa1ab3f31f33e6a4d051920ea24cd30ea347f4
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 106229cb39dfd3ad2b4768c7cd684aeb47922353
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 57a0d496b0fbcf42fb734919a7bee68aa758736d
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: ae4fb9f83c4c53aa28b000b7ac21f41aba74f6aa
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 90047cb5d779afe8dfeecd8a758e0da9f4f34939
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 7006e205f4288fb3dcf442b9c57e0f273989dd11
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 27f388ceb4a716e40f20dc716483e9a1c8d91a61
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 82d3c6393a7ae1b249f81c03714ee7a15b027eca
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: d9f75c8f02f98d9aa10e922a7ba050128df477d3
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: fe9a75ccdc5a6b88b3ec9dd210848e0d6cdde5b4
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 55aa3e3b802545a005bc1878211a2ca0527562c7
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 08428ec1f635bd7179c0408f86f61af6fcd3cd4f
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 3056938e04dbded2849f3f8d3bf64027510b7d29
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 74055a138a02d61ac2eeaa83f7e6a6b9c44ed898
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: ceae4e65a189fab046a48c59f642932171937fd9
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: b43c2c0d3850a85eed0eda142abcddaa46ac96a0
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: e0fb96fe3a185b056ba54874576eab4726d5d43c
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: f46e2bb9332ca7387cb41bf16bf24138bcbbde25
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: d71cdd365794005d31f314664ce0c2946fd3e31a
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 95bb5c92ac099219eed3a0f05d5e6337022a92e2
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 720e716304ed78dc19c18cf9a2562291a22775e4
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 5ce69fbd34089ca06bb3de3efa5ff5be53a323c5
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 954d73c0f1698f7722778828386fff25468731e1
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: a4506e8ddacc5f6360223289a58b94498f5a561c
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: b9d6464aa21e11629e0f3509c8ed2cb1f8a73999
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 59e1ce2abff4fb1f04e3774caa50cb2d08fb210e
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: b1aa1ab3f31f33e6a4d051920ea24cd30ea347f4
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 106229cb39dfd3ad2b4768c7cd684aeb47922353
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 57a0d496b0fbcf42fb734919a7bee68aa758736d
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: ae4fb9f83c4c53aa28b000b7ac21f41aba74f6aa
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 90047cb5d779afe8dfeecd8a758e0da9f4f34939
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 7006e205f4288fb3dcf442b9c57e0f273989dd11
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 27f388ceb4a716e40f20dc716483e9a1c8d91a61
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 82d3c6393a7ae1b249f81c03714ee7a15b027eca
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: d9f75c8f02f98d9aa10e922a7ba050128df477d3
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: fe9a75ccdc5a6b88b3ec9dd210848e0d6cdde5b4
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 55aa3e3b802545a005bc1878211a2ca0527562c7
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 08428ec1f635bd7179c0408f86f61af6fcd3cd4f
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 3056938e04dbded2849f3f8d3bf64027510b7d29
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 74055a138a02d61ac2eeaa83f7e6a6b9c44ed898
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: ceae4e65a189fab046a48c59f642932171937fd9
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: b43c2c0d3850a85eed0eda142abcddaa46ac96a0
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: e0fb96fe3a185b056ba54874576eab4726d5d43c
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: f46e2bb9332ca7387cb41bf16bf24138bcbbde25
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: d71cdd365794005d31f314664ce0c2946fd3e31a
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 95bb5c92ac099219eed3a0f05d5e6337022a92e2
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 720e716304ed78dc19c18cf9a2562291a22775e4
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 5ce69fbd34089ca06bb3de3efa5ff5be53a323c5
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 954d73c0f1698f7722778828386fff25468731e1
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: a4506e8ddacc5f6360223289a58b94498f5a561c
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: b9d6464aa21e11629e0f3509c8ed2cb1f8a73999
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 59e1ce2abff4fb1f04e3774caa50cb2d08fb210e
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: b1aa1ab3f31f33e6a4d051920ea24cd30ea347f4
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 106229cb39dfd3ad2b4768c7cd684aeb47922353
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 57a0d496b0fbcf42fb734919a7bee68aa758736d
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: ae4fb9f83c4c53aa28b000b7ac21f41aba74f6aa
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 90047cb5d779afe8dfeecd8a758e0da9f4f34939
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 7006e205f4288fb3dcf442b9c57e0f273989dd11
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 27f388ceb4a716e40f20dc716483e9a1c8d91a61
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 82d3c6393a7ae1b249f81c03714ee7a15b027eca
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: d9f75c8f02f98d9aa10e922a7ba050128df477d3
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: fe9a75ccdc5a6b88b3ec9dd210848e0d6cdde5b4
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 55aa3e3b802545a005bc1878211a2ca0527562c7
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 08428ec1f635bd7179c0408f86f61af6fcd3cd4f
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 3056938e04dbded2849f3f8d3bf64027510b7d29
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 74055a138a02d61ac2eeaa83f7e6a6b9c44ed898
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: ceae4e65a189fab046a48c59f642932171937fd9
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: b43c2c0d3850a85eed0eda142abcddaa46ac96a0
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: e0fb96fe3a185b056ba54874576eab4726d5d43c
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: f46e2bb9332ca7387cb41bf16bf24138bcbbde25
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: d71cdd365794005d31f314664ce0c2946fd3e31a
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 95bb5c92ac099219eed3a0f05d5e6337022a92e2
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 720e716304ed78dc19c18cf9a2562291a22775e4
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 5ce69fbd34089ca06bb3de3efa5ff5be53a323c5
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 954d73c0f1698f7722778828386fff25468731e1
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: a4506e8ddacc5f6360223289a58b94498f5a561c
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: b9d6464aa21e11629e0f3509c8ed2cb1f8a73999
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 59e1ce2abff4fb1f04e3774caa50cb2d08fb210e
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: cd4dbf31375710a3274ec66e4b0836c638acde87
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: b1aa1ab3f31f33e6a4d051920ea24cd30ea347f4
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 106229cb39dfd3ad2b4768c7cd684aeb47922353
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 57a0d496b0fbcf42fb734919a7bee68aa758736d
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: ae4fb9f83c4c53aa28b000b7ac21f41aba74f6aa
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 90047cb5d779afe8dfeecd8a758e0da9f4f34939
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 7006e205f4288fb3dcf442b9c57e0f273989dd11
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 27f388ceb4a716e40f20dc716483e9a1c8d91a61
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 82d3c6393a7ae1b249f81c03714ee7a15b027eca
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: d9f75c8f02f98d9aa10e922a7ba050128df477d3
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: fe9a75ccdc5a6b88b3ec9dd210848e0d6cdde5b4
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 55aa3e3b802545a005bc1878211a2ca0527562c7
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 08428ec1f635bd7179c0408f86f61af6fcd3cd4f
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 3056938e04dbded2849f3f8d3bf64027510b7d29
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 74055a138a02d61ac2eeaa83f7e6a6b9c44ed898
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: ceae4e65a189fab046a48c59f642932171937fd9
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: b43c2c0d3850a85eed0eda142abcddaa46ac96a0
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: e0fb96fe3a185b056ba54874576eab4726d5d43c
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: f46e2bb9332ca7387cb41bf16bf24138bcbbde25
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: d71cdd365794005d31f314664ce0c2946fd3e31a
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 95bb5c92ac099219eed3a0f05d5e6337022a92e2
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 720e716304ed78dc19c18cf9a2562291a22775e4
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 5ce69fbd34089ca06bb3de3efa5ff5be53a323c5
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 954d73c0f1698f7722778828386fff25468731e1
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: a4506e8ddacc5f6360223289a58b94498f5a561c
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: b9d6464aa21e11629e0f3509c8ed2cb1f8a73999
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 59e1ce2abff4fb1f04e3774caa50cb2d08fb210e
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: cd4dbf31375710a3274ec66e4b0836c638acde87
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by xendk** [comment]
Superseded by #614

**Pull request closed without merging**
