### PR TITLE
153 by Inlead: Disable form actions when syndicating own content.

### PR DESCRIPTION
**Pull request by AnatolyMuntean**
#### Link to issue

https://platform.dandigbib.org/issues/153

#### Description

Disable the ability to save the node form, when syndicating own content. Even-though the original link is removed from the bpi content overview it is still possible to use the node syndication URI by manually pasting it into the browser url bar. For such cases show a message and disable form actions at all.
Also, remove the syndication when previewing when previewing own content.

#### Screenshot of the result

Node form:
image
image

Preview (own content):
image

#### Checklist

- [x] My complies with [coding guidelines](../docs/code_guidelines.md).
- [x] My code passes static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [x] My code passes continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

### CODE REVIEW

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: f863efe90be21d359600d3aede3f0e92e0125b3b
  * The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: f863efe90be21d359600d3aede3f0e92e0125b3b
  * The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 91bbb118d7e1e4a0769e0036c74774d6c85c0522
  * The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 91bbb118d7e1e4a0769e0036c74774d6c85c0522
  * The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by kasperg** [comment]
@AnatolyMuntean: You checked "My code passes static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process." but Scruntinizer shows an increase in errors. 

While I agree that they can be disregarded, it is your responsibility to note that.

**Pull request merged**
