### PR TITLE
Issue 469 by Pjohans (original Morten Bartvig): Add module to set loc…

### PR DESCRIPTION
**Pull request by JrgenGNielsen**
…al configuration

### CODE REVIEW

**Comment by JrgenGNielsen** [comment]
More Scrutinizer error messages than I can fix - mostly error messages about incorrect line indentation.

**Comment by cableman** [comment]
After some conversion in the core team, we have concluded that we agree on the approach (hook_entity_view) but would like it to be part of the module that have the original configuration in this case ding_ting_frontend.

Maybe as a tab under "admin/config/ting/settings" with own permissions.

**Comment by holt83** [comment]
I'm curious as to why you would not use hook_ding_entity_view()?

hook_entity_view() seems to be called when viewing all entitites (nodes included). hook_ding_entity_view() on the other hand seems to only be called when viewing Ting objects, isn't that what we want?

**Comment by JrgenGNielsen** [comment]
Moved to: https://github.com/ding2/ding2/pull/165

**Pull request closed without merging**
