### PR TITLE
Issue #430 by Inlead: Change internal search to Search API.

### PR DESCRIPTION
**Pull request by guddo**
This PR changes the internal node search to utilize Search API.

API Index and API Server for Solr has been set up and exported, Solr needs to be installed locally on all instances (name: `ding2`, host: `localhost`).
If Solr is supposed to run as a generic instance, we can change this accordingly.

Currently the View displays the complete User entity (Staff) - therefore a small "hack" in the styling.
I would propose to customize the complete View and define Fields within Views UI and deprecate the Field UI Display Types used for current Search result.

http://platform.dandigbib.org/issues/430

### CODE REVIEW

**Comment by kasperg** [comment]
@guddo / @koykov: Stupid question, but have you verified that using Search API DB and Search API Multi together actually works?

One of my colleages has also been working with Search API Multi last week. He mentioned that it only works with Solr. [Documentation](http://cgit.drupalcode.org/search_api_multi/tree/README.txt#n6) and [issues](https://www.drupal.org/node/2010626) seems to support that.

**Comment by koykov** [comment]
@kasperg http://cgit.drupalcode.org/search_api_multi/tree/CHANGELOG.txt#n31

**Comment by kasperg** [comment]
@koykov: :+1:

**Comment by kasperg** [comment]
Reviewed and approved. Awaiting merge.

**Comment by kasperg** [comment]
Merged manually to fix conflicts. Thanks!

**Pull request merged**
