### PR TITLE
2671 by Inlead: Consider initialized slick carousels.

### PR DESCRIPTION
**Pull request by NicolaeGrigoriu**
https://platform.dandigbib.org/issues/2671

### CODE REVIEW

**Comment by cableman** [comment]
Please not that I'am working on new intergration with slick in https://platform.dandigbib.org/issues/1770

**Comment by NicolaeGrigoriu** [comment]
I think(~~hope~~ :) ) that these changes will not affect the way slick working.

**Comment by cableman** [comment]
They will stream-line the usage of carousels, so we don't use different libraries etc. But only uses slick (version 1.8) the same way across the site and only the library once etc.

**Comment by cableman** [comment]
See for more information https://github.com/ding2/ding2/pull/845

**Comment by guddo** [comment]
This line will most likely affect the IPE handling as well: https://github.com/ding2/ding2/pull/845/files#diff-1d4c6fc7228e5c51aed964a5d51b7b22R247

**Comment by cableman** [comment]
I'am closing this PR as the ting_carousel module have been removed from the codebase.

**Pull request closed without merging**
