### PR TITLE
2063 by Inlead: Various fixes for p2b.

### PR DESCRIPTION
**Pull request by avoykov**
http://platform.dandigbib.org/issues/2063

Fixes:
- Converts field_ding_event_price to string in order to define multiple prices for lists.
- Adds help text to field_ding_event_price field.
- Makes field_ding_event_price field required.
- Makes the module support various currencies.
- Makes sure that "Free" is shown if price is "0".
- Converts price value to kroner instead of ører.
- Disable migration module after migration has been run.
- Displays the postal code in the frontend.

### CODE REVIEW

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 171f8118dcde327a961b68ee0e0a63d4fa85f7b4
  * The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 171f8118dcde327a961b68ee0e0a63d4fa85f7b4
  * The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 171f8118dcde327a961b68ee0e0a63d4fa85f7b4
  * The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 171f8118dcde327a961b68ee0e0a63d4fa85f7b4
  * The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by JrgenGNielsen** [comment]
please rebase the commit message to comply with our contribution guidelines.

**Comment by guddo** [comment]
@JrgenGNielsen: Done!

**Comment by JrgenGNielsen** [comment]
reviewed and approved

**Pull request merged**
