### PR TITLE
4097: W3C Invalid syntax fixes

### PR DESCRIPTION
**Pull request by rasben**
#### Link to issue

https://platform.dandigbib.org/issues/4097

#### Description

These are minor fixes which makes the W3C HTML Validator happy

#### Checklist

- [x] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [x] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [x] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

### CODE REVIEW

**Comment by rasben** [comment]
Scrutinizer complains about my nesting in the template file, but I feel like implementing the requested changes would hurt readability. What is your opinion?

**Comment by JrgenGNielsen** [comment]
you can try the alternative syntax for control structures:
<?php if ($foo): ?>
foo
<?php endif; ?>
- otherwise, when in doubt, stick to Drupal standard :-)

**Comment by rasben** [comment]
Ok i've fixed it - but now scrutinizer complains about this which I dont think makes any sense:

screenshot 2019-02-15 at 11 06 16

So it wants me to do:

```php
<?php endif;
?>
```

which looks mad

**Comment by JrgenGNielsen** [comment]
reviewed and approved

**Pull request merged**
