### PR TITLE
4085: Added modified exposed form for events

### PR DESCRIPTION
**Pull request by martinyde**
#### Link to issue

https://platform.dandigbib.org/issues/4085

#### Description

Fix event list exposed views form to make it accessible.

#### Checklist

- [x] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [x] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [x] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

### CODE REVIEW

**Comment by kasperg** [comment]
We have had a problem with our PR environments on Platform.sh. I'll close/reopen the PR to rebuild.

**Comment by JrgenGNielsen** [comment]
please fix the Scrutinizer errors

**Comment by cableman** [comment]
The failing behat test is not related.

**Review by JrgenGNielsen — APPROVED** [review]
reviewed and approved

**Comment by JrgenGNielsen** [comment]
please fix the Scrutinizer errors.
also:
if($widget->id  -> if ($widget->id
 ^

**Comment by JrgenGNielsen** [comment]
reviewed and approved

**Pull request merged**
