### PR TITLE
2118: Removed dev dependencies from FBS

### PR DESCRIPTION
**Pull request by xendk**

### CODE REVIEW

**Comment by cableman** [comment]
Reviewed and approved

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 5cd8cf229097dae403722aeea7d63d4015312a6a
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 5cd8cf229097dae403722aeea7d63d4015312a6a
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by JrgenGNielsen** [comment]
Reviewed and approved

**Pull request merged**
