### PR TITLE
4598 by Inlead: Replace "Relevant Campaign" with "Relevant Campaign Plus"

### PR DESCRIPTION
**Pull request by NicolaeGrigoriu**
#### Link to issue

https://platform.dandigbib.org/issues/4598

#### Description

We should replace "Relevant Campaign" with "Relevant Campaign Plus" on frontpage and ding_section default page..

#### Checklist

- [x] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [x] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [x] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

### CODE REVIEW

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: c4d610e25d2a05ef398f9c53adee42ac59f5c0d8
  * The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: c4d610e25d2a05ef398f9c53adee42ac59f5c0d8
  * The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by holt83** [comment]
What about the campaign pane that is added to ding_section template during install: https://github.com/ding2/ding2/blob/master/modules/ding_sections/modules/ding_sections_term_panel/ding_sections_term_panel.module#L183?

Also, what about the campaign module and the several other exported panel pages that uses the old campaign type (see below)? If we're not going to use this module anymore shouldn't we do the full clean up? 
- https://github.com/ding2/ding2/blob/master/modules/ding_content/ding_content.pages_default.inc#L296
- https://github.com/ding2/ding2/blob/master/modules/ding_event/ding_event.pages_default.inc#L407
- https://github.com/ding2/ding2/blob/master/modules/ding_event/ding_event.pages_default.inc#L674
- https://github.com/ding2/ding2/blob/master/modules/ding_event/ding_event.pages_default.inc#L994
- https://github.com/ding2/ding2/blob/master/modules/ding_frontpage/ding_frontpage.pages_default.inc#L148 
- https://github.com/ding2/ding2/blob/master/modules/ding_groups/ding_groups.pages_default.inc#L154
- https://github.com/ding2/ding2/blob/master/modules/ding_library/ding_library.pages_default.inc#L567
- https://github.com/ding2/ding2/blob/master/modules/ding_library/ding_library.pages_default.inc#L748
- https://github.com/ding2/ding2/blob/master/modules/ding_news/ding_news.pages_default.inc#L653
- https://github.com/ding2/ding2/blob/master/modules/ding_news/ding_news.pages_default.inc#L993
- https://github.com/ding2/ding2/blob/master/modules/ding_news/ding_news.pages_default.inc#L1323
- https://github.com/ding2/ding2/blob/master/modules/ding_page/ding_page.pages_default.inc#L106
- https://github.com/ding2/ding2/blob/master/modules/ding_page/ding_page.pages_default.inc#L250
- https://github.com/ding2/ding2/blob/master/modules/ding_ting_frontend/ding_ting_frontend.pages_default.inc#L354
-https://github.com/ding2/ding2/blob/master/modules/ding_ting_frontend/ding_ting_frontend.pages_default.inc#L569
- https://github.com/ding2/ding2/blob/master/modules/ding_ting_frontend/ding_ting_frontend.pages_default.inc#L831

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: e0759eabf74a3749e165a7227d2fd26796f91e0c
  * The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: e0759eabf74a3749e165a7227d2fd26796f91e0c
  * The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by guddo** [comment]
@holt83 "ding_section template during install" was fixed. The issue was only to focus on this module and not the others.

**Pull request merged**
