### PR TITLE
1688: Fix mobile footer collapse icon

### PR DESCRIPTION
**Pull request by xendk**
The arrows to collapse/expand footer menu is wrong on mobile.

### CODE REVIEW

**Comment by cableman** [comment]
Please rebase this PR so it can be merged.

Reviewed and approved.

**Comment by xendk** [comment]
Done.

**Comment by cableman** [comment]
Awaiting next release.

**Comment by cableman** [comment]
Merged by hand to resolve merge conflict in compiled CSS.

**Pull request merged**
