### PR TITLE
Issue #775 by Inlead: Change submit button to link in reservation form.

### PR DESCRIPTION
**Pull request by guddo**
http://platform.dandigbib.org/issues/775

### CODE REVIEW

**Comment by kasperg** [comment]
The implementation of this change looks good. Reviewed and approved.

@NicolaeGrigoriu @guddo: From a technical perspective would any of you mind explaining why changing from a submit button to a link fixes the problem?

**Comment by guddo** [comment]
For some weird reason, Safari's focus wasn't in the ding_popup when it was a rendered button - changing it to a link (button-like style) and the browser understood to place the focus inside the popup.

**Comment by kasperg** [comment]
@guddo Thanks for explaining :tired_face:.

**Comment by kasperg** [comment]
Merged. Thanks!

**Pull request merged**
