### PR TITLE
Fixes #1867, #1869 and #1871 The old userprofile panel is removed 

### PR DESCRIPTION
**Pull request by martinb14**
http://platform.dandigbib.org/issues/1867
http://platform.dandigbib.org/issues/1871
http://platform.dandigbib.org/issues/1869

### CODE REVIEW

**Comment by cableman** [comment]
Commit message should be on the form:

[issue number]: [short summary of change]. The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

Only on issue and then the issue should be linked in the issue tracker.

**Comment by cableman** [comment]
The code is correct but it does not fix the issue: http://platform.dandigbib.org/issues/1871 as this is not the solution request and this alternative has not be approved in the issue tracker.

**Comment by cableman** [comment]
Also see comment in http://platform.dandigbib.org/issues/1869

**Comment by JrgenGNielsen** [comment]
reviewed and accepted

**Pull request merged**
