### PR TITLE
1604 by Inlead: Section-module problem

### PR DESCRIPTION
**Pull request by NicolaeGrigoriu**
#### Link to issue

http://platform.dandigbib.org/issues/1604

#### Description

No matter what Term panel variant I edit, all variants are being changed:
https://monosnap.com/file/Kfxqv4xhfMsKpttUWAJ50Noi8wnpS2

It should be pre-configured, so that News, Event and Page is checked in the settings upon installation.

The default variant should have the Frontpage layout (#4058).

#### Checklist

- [x] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [x] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [x] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

### CODE REVIEW

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 6f4e43da74bf1979a041fda89dc8a818137bd935
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 6f4e43da74bf1979a041fda89dc8a818137bd935
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 02341de4f719c77f24fb40c0aa736d91200c3cd7
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 02341de4f719c77f24fb40c0aa736d91200c3cd7
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by JrgenGNielsen** [comment]
Use of eval() is strongly discouraged. Please find another way to achieve the functionality.

**Comment by JrgenGNielsen** [comment]
reviewed and approved

**Pull request merged**
