### PR TITLE
Kill z index with fire

### PR DESCRIPTION
**Pull request by xendk**
Remove unnecessary z-indexes

The document order should ensure proper stacking order.

### CODE REVIEW

**Comment by guddo** [comment]
👍

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 8f591c17447f9f1a541feb760b382a9c6837cd8a
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 8f591c17447f9f1a541feb760b382a9c6837cd8a
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by xendk** [comment]
Aner ikke hvad der sker for Scrutinizer. Kan ikke engang se fejlen.

**Comment by cableman** [comment]
Reviewed and awaiting release

**Pull request merged**
