### PR TITLE
Issue 1104 by Pjohans: Add carousel config to shortcuts

### PR DESCRIPTION
**Pull request by pjohans**
Link in shortcut as suggested by Jesper - much better solution. Dismiss the old pr:
https://github.com/ding2/ding2/pull/56

### CODE REVIEW

**Comment by cableman** [comment]
Could the code be executed in ding_frontend_install() as well, so new sites (developer installation) also have the link available.

**Comment by pjohans** [comment]
done a new pull-request - please discard this one

**Comment by cableman** [comment]
Please fix the line comment found be Scrutinizer.

Everything else looks good.

**Comment by cableman** [comment]
New PR https://github.com/ding2/ding2/pull/213

**Pull request closed without merging**
