### PR TITLE
Issue550

### PR DESCRIPTION
**Pull request by pjohans**

### CODE REVIEW

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: b1197daba14796303038ac17556d224365ad5156
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: fbb4eeefc12171a590764b4df0b4a705a023d32b
  * The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

 * Commit: 2c662a61a4535fe2e7138e2d0d6cc57f15221772
  * The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

 * Commit: 4e8fbed925e1bf696cef89fb42de4d892883232f
  * The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

 * Commit: 76ec1eb23f4ec37c4211e9f5005725a7b655fc9c
  * The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: b1197daba14796303038ac17556d224365ad5156
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: fbb4eeefc12171a590764b4df0b4a705a023d32b
  * The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

 * Commit: 2c662a61a4535fe2e7138e2d0d6cc57f15221772
  * The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

 * Commit: 4e8fbed925e1bf696cef89fb42de4d892883232f
  * The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

 * Commit: 76ec1eb23f4ec37c4211e9f5005725a7b655fc9c
  * The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by kasperg** [comment]
@pjohans: Changes do still not apply with commit guidelines.

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 415cbd4ab8607bb5291758e4e79a0abd5b6dc119
  * The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 415cbd4ab8607bb5291758e4e79a0abd5b6dc119
  * The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by cableman** [comment]
Reviewed and approved

**Comment by kasperg** [comment]
Merged. Thanks!

**Pull request merged**
