### PR TITLE
3270 by Inlead: Cardinality violation upon Search.

### PR DESCRIPTION
**Pull request by bozeak**
https://platform.dandigbib.org/issues/3270

### CODE REVIEW

**Comment by cableman** [comment]
Maybe this belongs in ding_frontend as it has the dependency to search_api!

**Comment by bozeak** [comment]
This error was generated by calling and execution of "ding_multiple_search" view in search_backends.inc ting_search plugin (https://github.com/ding2/ding2/blob/master/modules/ting_search/plugins/content_types/search_backends.inc#L78) and this was main reason to keep it here.

**Comment by cableman** [comment]
Yes, but that view is stille defined in ding_frontend and not ting_search module

**Comment by cableman** [comment]
Reviewed and awaiting release

**Pull request merged**
