### PR TITLE
2304: Update Scheduler to 1.5

### PR DESCRIPTION
**Pull request by kasperg**
This fixes [a security vulnerability in 1.2](https://www.drupal.org/node/2373961). 

Updating to 1.3 causes notices to be raised which we do not want. The
patch for fixing this does not apply to 1.3. Consequently we update to 
the latest version instead, 1.5. This also means we can drop a patch 
which has been merged.

The new version introduces two new permissions which are updated in
secure permissions:

1. “schedule (un)publishing of nodes” is changed to “schedule 
publishing of nodes”
2. “view scheduled content” is introduces. This is added to roles
which already have “administer nodes” and “schedule 
publishing of nodes” permissions.

The new version may introduce new strings.

The new version introduces a few additional configuration options. We
use the defaults here.

### CODE REVIEW

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 6f977ab818849fb3e9bd0b51de8b57679c35c59b
  * Your commit message body contains a line that is longer than 72 characters
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 6f977ab818849fb3e9bd0b51de8b57679c35c59b
  * Your commit message body contains a line that is longer than 72 characters
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: fdae507815743c563b49863bb9836f595d144a7f
  * Your commit message body contains a line that is longer than 72 characters
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: fdae507815743c563b49863bb9836f595d144a7f
  * Your commit message body contains a line that is longer than 72 characters
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 3083e74ee124011cdbe55b0ca576f9c2d8f447dd
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 3083e74ee124011cdbe55b0ca576f9c2d8f447dd
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by kasperg** [comment]
I cannot tell which line in the commit message is longer than 72 chars. Can anyone help?

**Comment by guddo** [comment]
@kasperg: 4:70-4

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: e6506acb9a9a4e13c281fcbb67a8ca543d83c8f4
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: e6506acb9a9a4e13c281fcbb67a8ca543d83c8f4
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: a4da504610950052873de2d5a500f45efbdfccfc
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: a4da504610950052873de2d5a500f45efbdfccfc
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 95e3caa6e02516b861b1c68c56b87065317d79a9
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 95e3caa6e02516b861b1c68c56b87065317d79a9
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by kasperg** [comment]
@guddo: Thanks. Could you spell out which one? I am clearly not getting it right.

**Comment by kasperg** [comment]
I cleaned up some of the GitCop comments. It was getting out of hand.

I might also have deleted your comment @guddo. If so I apologies.

**Comment by kasperg** [comment]
Scrutizier issues are irrelevant. All raised issues are also fixed.

**Comment by guddo** [comment]
The [DDB CMS guidelines](https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md#pull-requests) says 69 chars (but strive for 50), and gitcop have previously said "69 characters". Did you change configuration?

L4 ("_patch for fixing this does not apply to 1.3. Consequently we update to_") in your commit is 70 characters.

**Comment by kasperg** [comment]
[The guidelines](https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md#pull-requests) say 

> The subject must not be more than 69 characters long.

The subject is the first line of the commit message so that should not apply to L4.

The guidelines do not say anything about body length - ie. all lines after the first. However GitCop is configured to warn after 72 characters. That seems to be the issue raised here.

I will try to write @GitCop 

ding2 2017-04-24 09-36-12

**Comment by guddo** [comment]
You are right, I was thinking about the guidelines for the subject..

**Comment by kasperg** [comment]
I have asked @GitCop about the issue.

**Comment by attritionorg** [comment]
@kasperg Can you link to a reference about the original vulnerability in Scheduler 1.2?

**Comment by kasperg** [comment]
@attritionorg: I have updated the initial PR comment with a link to the PSA.

**Comment by cableman** [comment]
Reviewed and awaiting release.

**Pull request merged**
