### PR TITLE
Issue #1629 by Inlead: Decode item title when reserving.

### PR DESCRIPTION
**Pull request by guddo**
http://platform.dandigbib.org/issues/1629

### CODE REVIEW

**Comment by kasperg** [comment]
Reviewed. I agree that this fixes the encoding issue in this specific but I am considering whether this is the right approach to a fix.

The problem indicates that we have reservations with encoded titles. I cannot spot anywhere else in the codebase where we decode reservation titles. In that case I would assume that we have the same encoding problem in the reservation list etc. If that is the case then I think we should aim for a fix closer to the root of the problem.

@guddo @AnatolyMuntean: How do you see this?

**Comment by guddo** [comment]
@kasperg: The difference between confirmation popup and reservation list could be usage of ding_entity vs ting_entity. Would you suggest to decode it in [getTitle() of ding_periodical](https://github.com/ding2/ding2/blob/master/modules/ding_periodical/ding_periodical_reservable.class.inc#L64) already?

**Comment by kasperg** [comment]
@guddo: Thanks for the quick followup.

I considered something like decoding it in `getTitle()` but I have not looked into the consequences and wanted to get your opinion of it.

Regarding usage of the different classes I cannot spot any decoding in either class. That leaves me wondering.

**Comment by AnatolyMuntean** [comment]
Decoding in `getTitle()` doesn't help. There was no deep dig into where it comes from encoded.

**Comment by kasperg** [comment]
OK. I guess we have to leave it at that. Approved and merged.

**Pull request merged**
