### PR TITLE
Issue1736

### PR DESCRIPTION
**Pull request by pjohans**

### CODE REVIEW

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: b1197daba14796303038ac17556d224365ad5156
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 0287f60e962b8ca5c1396d555c3fd88b65fcea7d
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: b1197daba14796303038ac17556d224365ad5156
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 0287f60e962b8ca5c1396d555c3fd88b65fcea7d
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: b1197daba14796303038ac17556d224365ad5156
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 0287f60e962b8ca5c1396d555c3fd88b65fcea7d
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: b1197daba14796303038ac17556d224365ad5156
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 0287f60e962b8ca5c1396d555c3fd88b65fcea7d
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by cableman** [comment]
It would be nice with a rebase that removes the two commits that's not part of the PR.

**Pull request merged**
