### PR TITLE
2308: Update Drupal Core to 7.54

### PR DESCRIPTION
**Pull request by kasperg**
Drupal 7.44 has several security vulnerabilities. Updating will fix 
these.

The new version introduces a new permission “administer fields”. This
permission is only granted to administrators

Updating also means we can drop a patch as the issue it addressed was 
fixed in 7.51.

Update documentation accordingly.

The new version may introduce new strings.

The new version may introduce a few additional configuration options.
We use the defaults here.

While we are at is we also drop FTP based downloading of Drupal Core.

### CODE REVIEW

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 0227e5951dba115b7962366b0460ced2066f49ab
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 0227e5951dba115b7962366b0460ced2066f49ab
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by cableman** [comment]
Reviewed and awaiting release

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 0227e5951dba115b7962366b0460ced2066f49ab
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 0227e5951dba115b7962366b0460ced2066f49ab
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
