### PR TITLE
1894: Revert upgrading Workflow module to 2.7

### PR DESCRIPTION
**Pull request by kasperg**
This also means we have to reapply patches.

Upgrading Workflow has introduced a range of other problems.

Creating a News node spawns errors:

- Workflow 1 cannot be loaded. Contact your system administrator. 

Workflow 1 cannot be loaded. Contact your system administrator.
Error: content 42 has no workflow attached. The data is not saved.
PDOException: SQLSTATE23000: Integrity constraint violation: 1048 Column 'field_bpi_workflow_value' cannot be null: INSERT INTO {field_data_field_bpi_workflow} (entity_type, entity_id, revision_id, bundle, delta, language, field_bpi_workflow_value) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6); Array ( [:db_insert_placeholder_0] => node [:db_insert_placeholder_1] => 42 [:db_insert_placeholder_2] => 122 [:db_insert_placeholder_3] => ding_news [:db_insert_placeholder_4] => 0 [:db_insert_placeholder_5] => und [:db_insert_placeholder_6] => ) i field_sql_storage_field_storage_write() (linje 514 af /var/aegir/platforms/ddb300rc2/modules/field/modules/field_sql_storage/field_sql_storage.module).

### CODE REVIEW

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: dac3965fffc5c3f2d07f5733c070101a25f3726d
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: dac3965fffc5c3f2d07f5733c070101a25f3726d
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by kasperg** [comment]
In effect this reverts the commits from #319.

**Comment by JrgenGNielsen** [comment]
reviewed and accepted

**Pull request merged**
