### PR TITLE
4362: smart search project - search results based on audit

### PR DESCRIPTION
**Pull request by KasperSkovNielsen**
#### Link to issue

https://platform.dandigbib.org/issues/4362

#### Description

This module makes it possible for assigned role to enhance search results by assigning alternate searches, boost specific values and/or add text, image and links to the search result page. 

#### Screenshot of the result

Screenshot_2019-05-22 Search Ting krimi Randers Bibliotek(1)

#### Checklist

- [in progress - should not be exempted] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [in progress - should not be exempted] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [in progress - should not be exempted] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

Cleanup of code in progress - python scripts will be omitted - PR will be ready for analysis by end of week. Will notify here and in issue #4362

### CODE REVIEW

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 5e580907adbf00a8969807636893f00003b3c0c8
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 5e580907adbf00a8969807636893f00003b3c0c8
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 5e580907adbf00a8969807636893f00003b3c0c8
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 5e580907adbf00a8969807636893f00003b3c0c8
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 5e580907adbf00a8969807636893f00003b3c0c8
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 5e580907adbf00a8969807636893f00003b3c0c8
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 5e580907adbf00a8969807636893f00003b3c0c8
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 5e580907adbf00a8969807636893f00003b3c0c8
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 5e580907adbf00a8969807636893f00003b3c0c8
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 5e580907adbf00a8969807636893f00003b3c0c8
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by KasperSkovNielsen** [comment]
Seems like drush_make still runs the first commited ding2.make file despite being fixed and committed later. Maybe the checks choke on the commit-message 5e58090 - fixed that with a rebase, but the old commit still get an error.
Should I make a new PR from a branch instead of master?
br kasperskov

**Comment by cableman** [comment]
It's always best to make a feature branch and make an PR from there. So that you have a clean master branch to rebase with ding2/master to sync with core and you have the freedom to make new PR's without altering existing PR's you made.

**Comment by KasperSkovNielsen** [comment]
Will do. This might fix the commit-massage and drush_make haywire also.

**Comment by KasperSkovNielsen** [comment]
new PR made
https://github.com/ding2/ding2/pull/1438
 - closing this.

**Pull request closed without merging**
