### PR TITLE
1672 by Inlead: Carousel makeover.

### PR DESCRIPTION
**Pull request by inlead**
http://platform.dandigbib.org/issues/1672

### CODE REVIEW

**Comment by xendk** [comment]
Mind explaining what this is supposed to do, as the referenced issue has already been merged?

Slick should stil be loaded via libraries API.

And does this affect transitions and progressive loading?

**Comment by guddo** [comment]
This makes it possible to insert the carousel several times, defining the setting of the specific carousel when inserted on the Panel (#199 and #145) instead of in a generic backend configuration form.

**Comment by guddo** [comment]
Issue no. 1672 is used for now, because I'm not sure whether it should be a standalone issue and/or how it should be merged with your makeover from #196.

**Comment by xendk** [comment]
I guess a new issue is probably best as #196 has already been merged. Business should be aware that we're replacing the old carousel JS library.

However, it boltches most of the work I did in #196. Looks like someone "resolved" merge conflicts by overwriting with their own version.

As it happens I was just looking into getting Slick in, so I'll take a look at this next week and see if I can backmerge pprogressive loading, etc. Do you have a copy of the brach before it was rebased you can push somewhere?

You wouldn't happen to have a working ting/addi config compo I might borrow for a week? I seem to have serious difficulty finding one.

**Comment by guddo** [comment]
You can find code here: https://github.com/easySuite/ding2/tree/easyopac/modules/ting_search_carousel - or I can submit a PR against a previous release here in ding2.

Write me an email and I'll send you some credentials to Moreinfo :)

**Comment by xendk** [comment]
I've gotten Slick and the makeover to play ball: #271

**Comment by DDBdrift** [comment]
https://platform.dandigbib.org/issues/1672 | Resloved (tag version)

**Pull request closed without merging**
