### PR TITLE
GitCop test

### PR DESCRIPTION
**Pull request by kasperg**
Duis lobortis massa imperdiet quam. Sed lectus. Cras ultricies mi eu turpis hendrerit fringilla. Praesent ac sem eget est egestas volutpat. Nulla neque dolor, sagittis eget, iaculis quis, molestie non, velit.

This commit should make GitCop complain.

### CODE REVIEW

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 16f415998e094934900a51e112faba37b552d14f
  * Your commit message body contains a line that is longer than 72 characters
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 16f415998e094934900a51e112faba37b552d14f
  * Your commit message body contains a line that is longer than 72 characters
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by kasperg** [comment]
Works fine 😄

**Comment by cableman** [comment]
Looks good 👍

**Comment by JrgenGNielsen** [comment]
:+1:

**Pull request closed without merging**
