### PR TITLE
1437: infomedia login

### PR DESCRIPTION
**Pull request by xendk**
Add login popup to infomedia articles.

### CODE REVIEW

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: cdec2b84623623f2cb4032dff7d93a02500eb6ea
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: cdec2b84623623f2cb4032dff7d93a02500eb6ea
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by xendk** [comment]
The scrutinizer failure is a bug. The line is indented correctly.

**Comment by JrgenGNielsen** [comment]
reviewed and approved

**Pull request merged**
