### PR TITLE
Issue #1426 by xendk: Supress scheduler validation on node save.

### PR DESCRIPTION
**Pull request by xendk**

### CODE REVIEW

**Comment by kasperg** [comment]
The build fails because the patch does not apply. Please look into this.

ding2 115 - circleci 2015-12-08 10-16-29

**Comment by koykov** [comment]
@kasperg I found the commit with a patch https://github.com/xendk/ding2/commit/919480f0218ba7421780d84b3a379ca40077c286

Patch https://www.drupal.org/files/issues/validation_interferes-2627370-2.patch is accessible. It seems, it's problem on CircleCI platform.

**Comment by xendk** [comment]
Fixed.

**Comment by JrgenGNielsen** [comment]
I've tested the build - and the patch apply nicely.

**Comment by JrgenGNielsen** [comment]
Reviewed and approved. Thanks!

**Comment by kasperg** [comment]
Merged.

**Pull request merged**
