### PR TITLE
4131: Ting Covers DDB

### PR DESCRIPTION
**Pull request by tripox**
#### Link to issue

https://platform.dandigbib.org/issues/4131

#### Description

Introduces Ting Covers Rest.
This module uses the new DDB cover service to fetch covers for the Ting Covers module.

The code contains an autogenerated client based on the OpenAPI specs [here](https://github.com/reload/ddb-coverservice-api/blob/master/coverservice-2.0.0.yaml) and a Docker command described in the `README.md` to regenerate the client code from an updated spec.

#### Checklist

- [x] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [x] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [x] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

* The [API](https://cover.dandigbib.org/api) still only returns an empty array, however it was tested against the Swagger Virtual Server API.
* This doesn't disable `ting_covers_addi`.
* Maybe it should be required to disable `ting_covers_addi`?

### CODE REVIEW

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: da3844aa1b46aa63b32b17b001af4bc80d97e8f6
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: d564777caf609600b732f8b4102c1332464aee30
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: c9cd4fe7ee05df178274eb9f5284bce6cca3ce9e
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 113c158c8fd50f6fdede721e43e8efc43c39d735
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: c4d8bd2f22f52fe502c5ef522e7562cef5bf40f6
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 3195f3322d0ea7135c1ba4257c707054a9a5539c
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: cd534d97be4e40753dfe668500860f5a2fa66f30
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 6d8f8b8bd364d4269d815858651a61e7df3a9117
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 6b337ba86ab51ede856b0cbcd113aa755c4970ed
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 1fc9d71941046e916ec6f9acd66ba575ce8ee9f0
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 234cfafb46e3b44ac18f832fa9a6ed77ff731bad
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 160bc422f98bb6ab2aec5e5c95dac7ab927ae77e
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 51df9002f80cc97c0a653779f54d0aa84f8ea915
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 4b92b4f854703881f2a4417e54e0982f87cfd61e
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 412cd1c6a173be5ffb1893e3146adcbb096acf5b
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 170f2946b2ddbb426f5571dd2d758c62b82518c3
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 0017ba4979358ebe8e87a22f39f3b39ab4be4647
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 090b897e28d52f6c6ba599b540756b17078c6941
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 072b47aa234682419fb275f38cadbc9989c8271d
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 18b96eeeefb2174289d07a7d55bb482214e3040b
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 65c2fd2d02423adb1b026b99cafff08859c7547b
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 8228456113cdd96039eadda500549a245b644eae
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 9dc7f529e0ed1bbbdcd6419647500f6dbf430d46
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: ef97e264aab0d2309956f1baa8ec5e0af2c46184
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 1556a294dd67336f45c3cf1ed74f4f12b49f7b76
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: f2f085e2066caba3df51d54de16b199c60a81770
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: e95f4be0f607a701d2f6236ef59fd5d61e7a322c
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 7d4d05d8b0e9a3840437d734dbcf55dc372e916c
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 323373fa4a4b25ea77f51f36d5ee0ce406352066
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 267337039edafb24c76294cf9c7827ad2d96cbb8
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: da3844aa1b46aa63b32b17b001af4bc80d97e8f6
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: d564777caf609600b732f8b4102c1332464aee30
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: c9cd4fe7ee05df178274eb9f5284bce6cca3ce9e
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 113c158c8fd50f6fdede721e43e8efc43c39d735
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: c4d8bd2f22f52fe502c5ef522e7562cef5bf40f6
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 3195f3322d0ea7135c1ba4257c707054a9a5539c
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: cd534d97be4e40753dfe668500860f5a2fa66f30
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 6d8f8b8bd364d4269d815858651a61e7df3a9117
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 6b337ba86ab51ede856b0cbcd113aa755c4970ed
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 1fc9d71941046e916ec6f9acd66ba575ce8ee9f0
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 234cfafb46e3b44ac18f832fa9a6ed77ff731bad
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 160bc422f98bb6ab2aec5e5c95dac7ab927ae77e
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 51df9002f80cc97c0a653779f54d0aa84f8ea915
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 4b92b4f854703881f2a4417e54e0982f87cfd61e
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 412cd1c6a173be5ffb1893e3146adcbb096acf5b
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 170f2946b2ddbb426f5571dd2d758c62b82518c3
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 0017ba4979358ebe8e87a22f39f3b39ab4be4647
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 090b897e28d52f6c6ba599b540756b17078c6941
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 072b47aa234682419fb275f38cadbc9989c8271d
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 18b96eeeefb2174289d07a7d55bb482214e3040b
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 65c2fd2d02423adb1b026b99cafff08859c7547b
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 8228456113cdd96039eadda500549a245b644eae
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 9dc7f529e0ed1bbbdcd6419647500f6dbf430d46
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: ef97e264aab0d2309956f1baa8ec5e0af2c46184
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 1556a294dd67336f45c3cf1ed74f4f12b49f7b76
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: f2f085e2066caba3df51d54de16b199c60a81770
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: e95f4be0f607a701d2f6236ef59fd5d61e7a322c
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 7d4d05d8b0e9a3840437d734dbcf55dc372e916c
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 323373fa4a4b25ea77f51f36d5ee0ce406352066
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

 * Commit: 267337039edafb24c76294cf9c7827ad2d96cbb8
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by tripox** [comment]
Scrutinizer fejler på den autogenererede kode. 
Jeg er usikker på, om der eksisterer et issue i forvejen, men ellers bør commits rettes til med issue nr.

**Comment by DDBdrift** [comment]
https://platform.dandigbib.org/issues/4131 | Closed

**Pull request closed without merging**
