### PR TITLE
B3163: Change the time interval for events

### PR DESCRIPTION
**Pull request by b14sha**
https://platform.dandigbib.org/issues/3163

### CODE REVIEW

**Comment by cableman** [comment]
Kode looks fine, but please rebase an re-export to match the core and the new features module.

**Comment by cableman** [comment]
I think something has gone wrong with the rebase. I don't see any changes to the time interval?

**Comment by JrgenGNielsen** [comment]
This PR deletes several field groups. Is this intended?

**Comment by kasperg** [comment]
Closed in favour of #1114

**Pull request closed without merging**
