### PR TITLE
2135: library cleanup (ding_libs)

### PR DESCRIPTION
**Pull request by xendk**
See https://platform.dandigbib.org/issues/2135

Move libraries to a common ding_libs module.

### CODE REVIEW

**Comment by xendk** [comment]
Scrutinizer errors are false positives.

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 2d16435de29aa5ae51d58153a95c74cfee9374b1
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 2d16435de29aa5ae51d58153a95c74cfee9374b1
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by cableman** [comment]
Please rebase to resolve conflict in ding2.install

**Comment by cableman** [comment]
Hi, should be composer.json file be moved from fbs, bpi modules to ding_lirbraris or how will the adapter find the file? Or is I missing something?

> $adapter->composerJson('composer.json');

**Comment by xendk** [comment]
```php
$adapter->composerJson('composer.json');
```

Is the composer.json in the individual libraries. It tells xautoload that it should load the composer.json for, say Guzzle, to find the classes that Guzzle implements.

The composer.json in fbs, etc. can still be used to tell xautoload which classes are included in the module.

**Comment by cableman** [comment]
Okay, thanks for the explanation :-)

**Comment by cableman** [comment]
Reviewed and awaiting release

**Pull request merged**
